import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { localeSwitcher } from '@/actions/home'
// import { getEpicIndonesianMovies } from '@/actions/home'

const inter = Inter({
  variable: '--font-inter-sans',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // await getEpicIndonesianMovies()
  return (
    <html lang='en'>
      <body className={`${inter.variable} mx-auto antialiased`}>
        {children}
        <form action={localeSwitcher} className='pb-[300px]'>
          <select name='locale-switcher'>
            <option value='id-ID'>Indonesia</option>
            <option value='es-ES'>Spanyol</option>
            <option value='de-DE'>Jerman</option>
            <option value='ko-KR'>Korea</option>
            {/* <option value='fr-FR'>Perancis</option> */}
            {/* <option value='no-NO'>Norwegia</option> */}
            {/* <option value='ru-RU'>Rusia</option> */}
            {/* <option value='en-AU'>Inggris (Australia)</option> */}
            {/* <option value='en-US'>Inggris (US)</option> */}
            <option value='zh-HK'>Chinese (Hongkong)</option>
            {/* <option value='zh-TW'>Chinese (Taiwan)</option> */}
          </select>
          <button type='submit'>Switch</button>
        </form>
      </body>
    </html>
  )
}
